repos:
-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: [--max-line-length=100]
      exclude: ^notebooks/
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    - id: interrogate
      args: [-vv, -i, --fail-under=80]
      additional_dependencies:
        - setuptools
      exclude: ^notebooks/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    - id: mypy
      args:
        - --explicit-package-bases
        - --ignore-missing-imports
      additional_dependencies: [types-requests]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
