name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: 🧾 Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install uv
      run: pip install uv
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e .
        pip install pytest
        pip install pre-commit  # Add this line to ensure pre-commit is installed
        pre-commit install
    - name: Run Pre-commit
      run: pre-commit run --all-files
    - name: Run Tests
      run: pytest tests/
